config/routes.rb
Reaper::Application.routes.draw do
  match "/parser/parse" => "parser#parse", :as => :parse
  root :to => "parser#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/parser_controller.rb
class ParserController < ApplicationController
  def index
  end

  def parse
    @html = Parser.new(params[:url], Bodypak.new).parse
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parser_helper.rb
module ParserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Reaper</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <!-- <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Reaper</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div>
      </div>
    </div> -->

    <div class="container">
      <div class="content">
        <div class="row">
            <%= yield %>
        </div><!--/row-->
      </div><!--/content-->

    </div> <!-- /container -->

    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/parser/index.html.erb
<div class="well">
<%= form_tag parse_path, :remote => true, :method => :post, :class => "url-form" do %>
  <div class="input-prepend my-wrapper">
    <span class="add-on">http://www.bodypak.pl/</span><%= text_field_tag :url, "", :class => "very-long" %><%= submit_tag "OK", :onclick => "$('#indicator').show();" %><div id="indicator"></div>
  </div>
<% end %>
</div>

<%= text_area_tag :content, "", :id => "textarea_content" %>

<div id="preview">
  <%= link_to "Pokaż podgląd..." %>
  <div id="content">
  </div>
</div>

app/views/parser/parse.html.erb
<h1>Parser#parse</h1>
<p>Find me in app/views/parser/parse.html.erb</p>

app/views/parser/parse.js.erb
var str = "<%= escape_javascript(@html) %>";
$("#textarea_content").text(str);
$("#preview div#content").hide().html(str);
$("#indicator").hide();